name: Android CI

on: 
  workflow_dispatch:
    inputs:
      Environment:
        description: 'Set the environment you need to take build'
        required: true
        default: 'prod'
        type: choice
        options:
        - prod
        - qeop
        - core
        - coreqe

      Flavour:
        description: 'What is the flavour?'
        required: true
        default: 'keyless'
        type: choice
        options:
        - keyless
        - progress
        - kairos
        - nhr


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
        
    - name: Validate Gradle Wrapper 
      uses: gradle/actions/wrapper-validation@v4
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.3
      with:
        node-version: '20'

    - name: Configure npm for GitHub Packages
      run: |
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}" > ~/.yarnrc

    - name: Install Node Modules
      run: yarn

    - name: Env setup
      run: |
        export PLATFORM='android' FLAVOUR=${{ inputs.Flavour }} ENV=${{ inputs.Environment }}
        yarn setup

    - name: Fixable Eslint
      run: yarn lint

    - name: Grant execute permission for gradlew
      run: |
          cd android
          chmod +x gradlew

    - name: Clean Android
      run: yarn cleanAndroid
            
    - name: Build with Gradle
      run: |
            cd android
            ./gradlew build
            cd ..

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.4.0
      with:
        name: "android_build"
        path: ./android/app/build/outputs/apk/release/app-release.apk
        retention-days: 1
