name: Android CI

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
        
    - name: Validate Gradle Wrapper 
      uses: gradle/actions/wrapper-validation@v4
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.3
      with:
        node-version: '20'

    - name: Run Yarn Install
      run: yarn install 

    - name: Install Node Modules
      run: yarn

    - name: Fixable Eslint
      run: yarn lint

    - name: Grant execute permission for gradlew
      run: |
          cd android
          chmod +x gradlew
          
    - name: Print React Native Config
      run: npx react-native config   

    - name: Clean Android
      run: yarn cleanAndroid
            
    - name: Build with Gradle
      run: |
            cd android
            ./gradlew build
            cd ..

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.2.1-node20
      with:
        name: "android_build"
        path: ./android/app/build/outputs/apk/app-release.apk
        retention-days: 1
